Matchtitle: "PetMatch"
remote_theme: just-the-docs/just-the-docs
markdown: kramdown
search_enabled: true
search_tokenizer_separator: /[\s/]+/
mermaid:
  version: "10.5.0" # Optional, für Diagramme
callouts:
  tip:
    title: "🤍 Tipp"
    color: "#4caf50"  # Grün für hilfreiche Tipps
  info:
    title: "ℹ️ Info"
    color: "#2196f3" # Blau für allgemeine Informationen
  attention:
    title: "❕ Achtung"
    color: "#ff5722" # Orange für Warnungen
  download:
    title: "💾 Download"
    color: "#607d8b" # Dunkelgrau für Downloads
